# bStats (https://bStats.org) collects some basic information for plugin authors, like how
# many people use their plugin and their total player count. It's recommended to keep bStats
# enabled, but if you're not comfortable with this, you can turn this setting off. There is no
# performance penalty associated with having metrics enabled, and data sent to bStats is fully anonymous.

version: 1.1.03

# Some settings in the config have been typed shorter so as not to clutter it too much. Please visit:
# https://github.com/JeannotM/DynamicDifficulty or https://www.spigotmc.org/resources/dynamic-difficulty.92025/
# for more detailed explanations with examples.

# Affinity Gained or Lost When Doing Certain Things.
points-on-interval: 5 # How many points to give per interval, if turned on.
block-mined: 1
player-hit: -1
pvp-kill: 20
pve-kill: 1
death: -80

# With How Much Affinity a Player Starts When Joining For The First Time.
starting-affinity: 500

# What The Maximum and Minimum Affinity Are, no one can get more or less than this (even with commands)
min-affinity: 0
max-affinity: 1200

# 0 Equals Disabled, timer is in minutes
interval-timer: 1

# Mobs That Will Give Points From "pve-kill" when killed: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Format:
# - MOBTYPE: <Affinity points>
# Will use pve-kill if only MOBTYPE is given
mobs-count-as-pve:
- ZOMBIE
- BLAZE: 2
- CREEPER: 2
- SKELETON
- ENDERMAN: 3
- WITHER_SKELETON: 3
- SPIDER
- CAVESPIDER: 2
- VINDICATOR: 3
- WITCH
- VILLAGER: 20

# Blocks That Will Give Points From "block-mined" when mined: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocks:
- DIAMOND_ORE
- EMERALD_ORE

# whether to hook into some other plugins or not. (List may be expanded in the future)
plugin-support:
  allow-papi: false # Check the Github or Spigot page for the commands
  allow-bstats: true # To Only Disable it on DynamicDifficulty (enabling bstats here when it's disabled won't work)
  use-prefix: true

saving-data:
  type: file # Supported : file, mysql
#  port: "3306"
#  host: "localhost"
#  username: "root"
#  password: ""
#  database: "dynamicdifficulty"

# You can disable DynamicDifficulty in certain worlds if Multiverse is enabled
# disabled-worlds:
# - example_name

# Whether the Player Will Receive Affinity When Mining Blocks With Silk Touch
silk-touch-allowed: false

# Calculates the percentage between 2 difficulties so the progression will feel more natural.
calculate-exact-percentage: true

# Will calculate difficulty per player if enabled, will otherwise do that for the whole world (everyone will be on the same difficulty)
per-player-difficulty: true

# This has been calculated from the hard difficulty. So it is recommended to change these if you're not playing on hard world difficulty
# Only "effects-when-attacked" affect the Wither and EnderDragon
# Copy one of the existing difficulty settings to create your own, check the Github page for more info
difficulty:
  Easy:
    affinity-required: 0
    damage-done-by-mobs: 50
    damage-done-on-mobs: 100
    experience-multiplier: 70
    double-loot-chance: 0
    effects-when-attacked: false
    prefix: '&7&l[&b&lEasy&7&l]&r'
  Normal:
    affinity-required: 400
    damage-done-by-mobs: 75
    damage-done-on-mobs: 100
    experience-multiplier: 90
    double-loot-chance: 0
    effects-when-attacked: true
    prefix: '&7&l[&9&lNormal&7&l]&r'
  Hard:
    affinity-required: 1000
    damage-done-by-mobs: 100
    damage-done-on-mobs: 100
    experience-multiplier: 125
    double-loot-chance: 5
    effects-when-attacked: true
    prefix: '&7&l[&4&lHard&7&l]&r'