# bStats (https://bStats.org) collects some basic information for plugin authors, like how
# many people use their plugin and their total player count. It's recommended to keep bStats
# enabled, but if you're not comfortable with this, you can turn this setting off. There is no
# performance penalty associated with having metrics enabled, and data sent to bStats is fully anonymous.

version: 1.5

# Some info in the config have been typed shorter so as not to clutter it too much. Please visit for more detailed explanations with examples:
# https://github.com/JeannotM/DynamicDifficulty or https://www.spigotmc.org/resources/dynamic-difficulty.92025/

# Affinity Gained or Lost When Doing Certain Things.
points-per-minute: 3
block-mined: 2
player-hit: -1
pvp-kill: 20
pve-kill: 2
death: -80

# How Much Affinity a Player Starts With When Joining For The First Time.
starting-affinity: 600
starting-min-affinity: 0
starting-max-affinity: 1500

# What The Maximum and Minimum Affinity Are, no one can get more or less than this (even with commands)
min-affinity: 0
max-affinity: 1500

# Mobs that will give affinity, Will use "pve-kill" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# - MOBTYPE: <Affinity points>
mobs-count-as-pve:
- BLAZE: 4
- CAVE_SPIDER: 3
- CREEPER: 3
- DROWNED
- ENDER_DRAGON: 100
- ELDER_GUARDIAN: 20
- ENDERMAN: 5
- GUARDIAN: 3
- HUSK
- IRON_GOLEM: 50
- MAGMA_CUBE
- PHANTOM
- PIGLIN
- PIGLIN_BRUTE: 5
- SKELETON
- SPIDER
- VILLAGER: 20
- VINDICATOR: 5
- WITCH
- WITHER: 100
- WITHER_SKELETON: 5
- ZOMBIE

# Blocks that will give affinity, Will use "block-mined" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# - BLOCKTYPE: <Affinity points>
blocks:
- ANCIENT_DEBRIS: 4
- DIAMOND_ORE
- EMERALD_ORE

# Whether the Player Will Receive Affinity When Mining Blocks With Silk Touch
silk-touch-allowed: false

# Whether to Hook Into certain Plugins or not
plugin-support:
  allow-papi: false # Check the Github or Spigot page for the commands
  allow-bstats: true # To Only Disable BStats for DynamicDifficulty
  use-prefix: true
  no-changes-to-spawned-mobs: false # Mobs that spawn from eggs or spawners, won't have damage, loot or other changes. Players will also NOT receive any Affinity from these mobs.
  unload-leaving-player: false # Removes a few issues with not being able to find certain players. Enabling it will improve ram a few kb's, but may cause some problems that were stated earlier.

saving-data:
  type: file # Supported: none, file, mysql, sqlite, mongodb, postgresql
#  port: 3306
#  host: localhost
#  username: root
#  password:
#  database: dynamicdifficulty

# You can disable DynamicDifficulty in certain worlds
disabled-worlds:
- example_name

# These mobs ignore everything except the "effects-when-attacked" and "mobs-ignore-player" settings from difficulty
disabled-mobs:
- ENDER_DRAGON
- ELDER_GUARDIAN
- WITHER

difficulty-modifiers:
  type: player # Supported: player, world
  randomize: false # randomizes all difficulty settings for everyone (uses the settings at the end of the page)
  exact-percentage: true # Calculates the percentage between 2 difficulties so the progression will feel more natural
  # Multiplies all the difficulty values by x amount (100 * 2.5 = 250)
  damage-done-by-mobs-multiplier: 1.0
  damage-done-on-mobs-multiplier: 1.0
  double-loot-chance-multiplier: 1.0
  experience-multiplier: 1.0

# This has been calculated from the hard difficulty. So it is recommended to change these if you're not playing on hard world difficulty
# More information if you want to make your own difficulty (I'd recommend copying one of the other difficulties and changing values):
# <custom_name>:
#   affinity-required: <number, At What affinity this difficulty starts working>
#   damage-done-by-mobs: <percentage, How much damage mobs do to you>
#   damage-done-on-mobs: <percentage, How much damage you do on mobs>
#   hunger-drain-chance: <percentage, Chance that the hunger of a player will drain>
#   damage-done-by-ranged-mobs: <percentage, How much damage projectiles do>
#   double-durability-damage-chance: <percentage, Chance to take double damage on item durability>
#   experience-multiplier: <percentage, Experience Multiplier>
#   double-loot-chance: <percentage, Chance to double the loot dropped when a mob is killed>
#   allow-pvp: <bool, Whether the player can attack or be attacked by other players>
#   keep-inventory: <bool, Whether the player keeps everything on death or not>
#   effects-when-attacked: <bool, Whether you get poison/wither etc from mob attacks (not including splash potions), works only on normal/hard world difficulty>
#   prefix: <text, prefix to return if PlaceholderAPI is enabled>
#   extra-damage-for-certain-armor-types: <list, how much damage reduction/increased per armor set worn (full diamond on Hard = 100 + (4 * 4)). Settings include: [nothing, leather, golden, chainmail, iron, turtle, elytra, diamond and netherite]>
#   mobs-ignore-player: <list, these mobs will ignore the players unless they're provoked>
difficulty:
  Easy:
    affinity-required: 0
    damage-done-by-mobs: 50
    damage-done-on-mobs: 100
    hunger-drain-chance: 60
    damage-done-by-ranged-mobs: 75
    double-durability-damage-chance: 0
    experience-multiplier: 70
    double-loot-chance: 0
    keep-inventory: true
    allow-pvp: true
    effects-when-attacked: false
    prefix: '&7&l[&b&lEasy&7&l]&r'
    extra-damage-for-certain-armor-types:
      nothing: -3
      leather: -1
    mobs-ignore-player:
    - CREEPER
  Normal:
    affinity-required: 400
    damage-done-by-mobs: 75
    damage-done-on-mobs: 100
    hunger-drain-chance: 80
    damage-done-by-ranged-mobs: 100
    double-durability-damage-chance: 1
    experience-multiplier: 90
    double-loot-chance: 0
    allow-pvp: true
    keep-inventory: false
    effects-when-attacked: true
    prefix: '&7&l[&9&lNormal&7&l]&r'
  Hard:
    affinity-required: 1100
    damage-done-by-mobs: 100
    damage-done-on-mobs: 100
    hunger-drain-chance: 100
    damage-done-by-ranged-mobs: 125
    double-durability-damage-chance: 5
    experience-multiplier: 125
    double-loot-chance: 5
    allow-pvp: true
    keep-inventory: false
    effects-when-attacked: true
    prefix: '&7&l[&4&lHard&7&l]&r'
    extra-damage-for-certain-armor-types:
      golden: 1
      chainmail: 1
      iron: 2
      diamond: 4
      netherite: 5

# Some of these features are experimental, change existing features or have a chance to reduce server performance
advanced-features:
  # The 'auto-calculate' features will, add and remove min/max affinity from players depending on configured settings
  # These WILL override existing min/max affinity settings.
  auto-calculate-min-affinity: false
  auto-calculate-max-affinity: false
  custom-mob-items-spawn-chance: false

# Difficulty name NEEDS to be EXACTLY the same as the ones in 'difficulty'
custom-mob-items-spawn-chance:
  override-default-limits: false # will allow higher levels than Minecraft's defaults. (E.g. Unbreaking 7 can happen if max-level is higher or equals 7)
  override-enchant-conflicts: false # Allows conflicting enchants to occur on a single armor (E.g. Protection & Fire Protection)
  # These are the only mobs that will spawn with these custom settings
  # You can add any mob you want, but some will not show any armor. So it's not recommended going too wild
  includes-mobs:
  - ZOMBIE
  - SKELETON
  weapons-include:
  - WOODEN_SHOVEL: 200
  - GOLDEN_SHOVEL: 50
  - IRON_SHOVEL: 5
  - WOODEN_AXE: 200
  - GOLDEN_AXE: 50
  - IRON_AXE: 5
  - WOODEN_PICKAXE: 200
  - GOLDEN_PICKAXE: 50
  - IRON_PICKAXE: 5
  - WOODEN_SWORD: 200
  - GOLDEN_SWORD: 50
  - IRON_SWORD: 5
  armor-set-weight:
    leather: 3706
    gold: 4872
    chainmail: 1290
    iron: 127
    diamond: 4
    netherite: 1
  # https://www.digminecraft.com/lists/enchantment_list_pc.php
  # You'll have to use the names that are beneath the names with those __snakes__
  helmet-enchants-include:
  #- <ENCHANT_NAME>: WEIGHT, higher means more likely to occur, no value = weight of 1
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - aqua_affinity: 2
  - thorns
  - respiration: 2
  - unbreaking: 5
  chestplate-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  leggings-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  boots-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - feather_falling: 5
  - thorns
  - frost_walker: 2
  - soul_speed
  - depth_strider: 2
  - unbreaking: 5
  weapon-enchants-include:
  - sharpness: 10
  - bane_of_arthropods: 5
  - smite: 5
  - fire_aspect: 2
  - looting: 2
  - knockback: 2
  - sweeping: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5
  bow-enchants-include:
  - power: 10
  - flame: 2
  - infinity
  - punch: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5
  # You'll need to use the EXACT same name as in difficulties.
  # (E.g. if Extreme difficulty exists, but not here; will use the last difficulty that had any settings changed)
  difficulties:
    Easy:
      max-enchants: 1
      max-level: 1
      chance-to-have-armor: 5.0
      chance-to-enchant-a-piece: 15
      armor-drop-chance: 10.0
      weapon-drop-chance: 5.0
      weapon-chance: 1.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
    Normal:
      max-enchants: 2
      max-level: 1
      chance-to-have-armor: 15.0
      chance-to-enchant-a-piece: 30
      armor-drop-chance: 15.0
      weapon-drop-chance: 10.0
      weapon-chance: 2.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
    Hard:
      max-enchants: 3
      max-level: 2
      chance-to-have-armor: 20.0
      chance-to-enchant-a-piece: 45
      armor-drop-chance: 20.0
      weapon-drop-chance: 15.0
      weapon-chance: 5.0
      helmet-chance: 100.0
      chest-chance: 90.0
      leggings-chance: 81.0
      boots-chance: 72.9

# This section is to calculate the min & max affinity of players automatically, WILL OVERRIDE existing values.
calculating-affinity:
  # Will check equipment every few minutes
  minute-interval-per-checking-equipment: 5
  min-affinity-changes:
    # Affinity limit is counted from the min-affinity set at the top (0 + 700 = 700)
    affinity-limit: 700
    points-per-minute: 1
    block-mined: 1
    player-hit: -1
    pvp-kill: 5
    pve-kill: 1
    death: -100
    items-held-or-worn:
    - IRON_HELMET: 2
    - IRON_CHESTPLATE: 4
    - IRON_LEGGINGS: 2
    - IRON_BOOTS: 2
    - DIAMOND_HELMET: 4
    - DIAMOND_CHESTPLATE: 6
    - DIAMOND_LEGGINGS: 4
    - DIAMOND_BOOTS: 4
    - NETHERITE_HELMET: 6
    - NETHERITE_CHESTPLATE: 8
    - NETHERITE_LEGGINGS: 6
    - NETHERITE_BOOTS: 6
    - ELYTRA: 10
    - IRON_SWORD: 1
    - IRON_PICKAXE: 1
    - IRON_AXE: 1
    - DIAMOND_SWORD: 3
    - DIAMOND_PICKAXE: 3
    - DIAMOND_AXE: 3
    - NETHERITE_SWORD: 5
    - NETHERITE_PICKAXE: 5
    - NETHERITE_AXE: 5
    - GOLDEN_APPLE: 5
    - ENCHANTED_GOLDEN_APPLE: 10
  max-affinity-changes:
    # Affinity limit is counted from the max-affinity set at the top (1500 - 700 = 800)
    affinity-limit: 700
    points-per-minute: -2
    block-mined: -1
    player-hit: 1
    pvp-kill: -4
    pve-kill: -1
    death: 100
    items-held-or-worn:
    - IRON_HELMET: -1
    - IRON_CHESTPLATE: -2
    - IRON_LEGGINGS: -1
    - IRON_BOOTS: -1
    - DIAMOND_HELMET: -3
    - DIAMOND_CHESTPLATE: -4
    - DIAMOND_LEGGINGS: -3
    - DIAMOND_BOOTS: -3
    - NETHERITE_HELMET: -5
    - NETHERITE_CHESTPLATE: -8
    - NETHERITE_LEGGINGS: -5
    - NETHERITE_BOOTS: -5
    - ELYTRA: -10
    - IRON_SWORD: -1
    - IRON_PICKAXE: -1
    - IRON_AXE: -1
    - DIAMOND_SWORD: -3
    - DIAMOND_PICKAXE: -3
    - DIAMOND_AXE: -3
    - NETHERITE_SWORD: -5
    - NETHERITE_PICKAXE: -5
    - NETHERITE_AXE: -5
    - GOLDEN_APPLE: -5
    - ENCHANTED_GOLDEN_APPLE: -15