# bStats (https://bStats.org) collects some basic information for plugin authors, like how
# many people use their plugin and their total player count. It's recommended to keep bStats
# enabled, but if you're not comfortable with this, you can turn this setting off. There is no
# performance penalty associated with having metrics enabled, and data sent to bStats is fully anonymous.

version: 1.4

# Some info in the config have been typed shorter so as not to clutter it too much. Please visit for more detailed explanations with examples:
# https://github.com/JeannotM/DynamicDifficulty or https://www.spigotmc.org/resources/dynamic-difficulty.92025/

# Affinity Gained or Lost When Doing Certain Things.
points-per-minute: 3
block-mined: 2
player-hit: -1
pvp-kill: 20
pve-kill: 2
death: -80

# How Much Affinity a Player Starts With When Joining For The First Time.
starting-affinity: 500

# What The Maximum and Minimum Affinity Are, no one can get more or less than this (even with commands)
min-affinity: 0
max-affinity: 1200

# Mobs that will give affinity, Will use "pve-kill" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# - MOBTYPE: <Affinity points>
mobs-count-as-pve:
- BLAZE: 4
- CAVE_SPIDER: 3
- CREEPER: 3
- DROWNED
- ENDER_DRAGON: 100
- ELDER_GUARDIAN: 20
- ENDERMAN: 5
- GUARDIAN: 3
- HUSK
- IRON_GOLEM: 50
- MAGMA_CUBE
- PHANTOM
- PIGLIN
- PIGLIN_BRUTE: 5
- SKELETON
- SPIDER
- VILLAGER: 20
- VINDICATOR: 5
- WITCH
- WITHER: 100
- WITHER_SKELETON: 5
- ZOMBIE

# Blocks that will give affinity, Will use "block-mined" if no value was specified: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# - BLOCKTYPE: <Affinity points>
blocks:
- ANCIENT_DEBRIS: 4
- DIAMOND_ORE
- EMERALD_ORE

# Whether the Player Will Receive Affinity When Mining Blocks With Silk Touch
silk-touch-allowed: false

# Whether to Hook Into certain Plugins or not
plugin-support:
  allow-papi: false # Check the Github or Spigot page for the commands
  allow-bstats: true # To Only Disable BStats for DynamicDifficulty
  use-prefix: true
  unload-leaving-player: false # Removes a few issues with not being able to find certain players, enabling it will also improve ram usage a little.

saving-data:
  type: file # Supported: none, file, mysql, sqlite, mongodb, postgresql
#  port: 3306
#  host: localhost
#  username: root
#  password:
#  database: dynamicdifficulty

# Disable DynamicDifficulty in certain worlds
# disabled-worlds:
# - example_name

# These mobs ignore everything except the "effects-when-attacked" and "mobs-ignore-player" settings from difficulty
disabled-mobs:
- ENDER_DRAGON
- ELDER_GUARDIAN
- WITHER

difficulty-modifiers:
  type: player # Supported: player, world
  randomize: false # randomizes all difficulty settings for everyone (uses the settings at the end of the page)
  exact-percentage: true # Calculates the percentage between 2 difficulties so the progression will feel more natural
  # Multiplies all the difficulty values by x amount (100 * 2.5 = 250)
  damage-done-by-mobs-multiplier: 1.0
  damage-done-on-mobs-multiplier: 1.0
  double-loot-chance-multiplier: 1.0
  experience-multiplier: 1.0

# This has been calculated from the hard difficulty. So it is recommended to change these if you're not playing on hard world difficulty
# Copy one of the existing difficulty settings to create your own, check the Github page for more info
difficulty:
  Easy:
    affinity-required: 0
    damage-done-by-mobs: 50
    damage-done-on-mobs: 100
    hunger-drain-chance: 60
    experience-multiplier: 70
    double-loot-chance: 0
    keep-inventory: true
    effects-when-attacked: false
    prefix: '&7&l[&b&lEasy&7&l]&r'
    mobs-ignore-player:
    - CREEPER
  Normal:
    affinity-required: 400
    damage-done-by-mobs: 75
    damage-done-on-mobs: 100
    hunger-drain-chance: 80
    experience-multiplier: 90
    double-loot-chance: 0
    keep-inventory: false
    effects-when-attacked: true
    prefix: '&7&l[&9&lNormal&7&l]&r'
  Hard:
    affinity-required: 1000
    damage-done-by-mobs: 100
    damage-done-on-mobs: 100
    hunger-drain-chance: 100
    experience-multiplier: 125
    double-loot-chance: 5
    keep-inventory: false
    effects-when-attacked: true
    prefix: '&7&l[&4&lHard&7&l]&r'

# Some of these features are experimental, change existing features or have a chance to reduce performance
advanced-features:
  # The 'auto-calculate' features will, add and remove min/max affinity from players depending on configured settings
  # These WILL override existing min/max affinity settings.
  auto-calculate-min-affinity: false
  auto-calculate-max-affinity: false
  custom-mob-items-spawn-chance: false

# Difficulty name NEEDS to be EXACTLY the same as the ones in 'difficulty'
custom-mob-items-spawn-chance:
  override-default-limits: false # will allow higher levels than Minecraft's defaults. (E.g. Unbreaking 7 can happen if max-level is higher or equals 7)
  override-enchant-conflicts: false # Allows conflicting enchants to occur on a single armor (E.g. Protection & Fire Protection)
  includes-mobs:
  - ZOMBIE
  - SKELETON
  weapons-include:
  - WOODEN_SHOVEL
  - GOLDEN_SHOVEL
  - IRON_SHOVEL
  - WOODEN_AXE
  - GOLDEN_AXE
  - IRON_AXE
  - WOODEN_PICKAXE
  - GOLDEN_PICKAXE
  - IRON_PICKAXE
  - WOODEN_SWORD
  - GOLDEN_SWORD
  - IRON_SWORD
  armor-set-weight:
    leather: 3706
    gold: 4872
    chain: 1290
    iron: 127
    diamond: 4
    netherite: 1
  # https://www.digminecraft.com/lists/enchantment_list_pc.php
  helmet-enchants-include:
  #- <ENCHANT_NAME>: WEIGHT, higher means more likely to occur, no value = weight of 1
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - aqua_affinity: 2
  - thorns
  - respiration: 2
  - unbreaking: 5
  chestplate-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  leggings-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - thorns
  - unbreaking: 5
  boots-enchants-include:
  - protection: 10
  - blast_protection: 5
  - fire_protection: 5
  - projectile_protection: 5
  - vanishing_curse
  - binding_curse
  - feather_falling: 5
  - thorns
  - frost_walker: 2
  - soul_speed
  - depth_strider: 2
  - unbreaking: 5
  weapon-enchants-include:
  - sharpness: 10
  - bane_of_arthropods: 5
  - smite: 5
  - fire_aspect: 2
  - looting: 2
  - knockback: 2
  - sweeping: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5
  bow-enchants-include:
  - power: 10
  - flame: 2
  - infinity
  - punch: 2
  - vanishing_curse
  - binding_curse
  - unbreaking: 5
  difficulties:
    Easy:
      max-enchants: 1
      max-level: 1
      chance-to-have-armor: 5.0
      chance-to-enchant-a-piece: 15
      armor-drop-chance: 10.0
      weapon-chance: 1.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
    Normal:
      max-enchants: 2
      max-level: 1
      chance-to-have-armor: 15.0
      chance-to-enchant-a-piece: 30
      armor-drop-chance: 15.0
      weapon-chance: 2.0
      helmet-chance: 100.0
      chest-chance: 75.0
      leggings-chance: 56.25
      boots-chance: 42.19
    Hard:
      max-enchants: 3
      max-level: 2
      chance-to-have-armor: 20.0
      chance-to-enchant-a-piece: 45
      armor-drop-chance: 20.0
      weapon-chance: 5.0
      helmet-chance: 100.0
      chest-chance: 90.0
      leggings-chance: 81.0
      boots-chance: 72.9

# This section is to calculate the min & max affinity of players automatically, WILL OVERRIDE existing values.
calculating-affinity:
  # this setting whether to check every minute or if a player equips/holds an item.
  check-equipment: every-5-minutes # Supported: every-minute, every-5-minutes, on-equip
  min-affinity-changes:
    affinity-limit: 500
    points-per-minute: -1
    block-mined: 1
    player-hit: 0
    pvp-kill: 1
    pve-kill: 5
    death: -50
    items-held-or-worn:
    - IRON_HELMET: 5
    - IRON_CHESTPLATE: 10
    - IRON_LEGGINGS: 5
    - IRON_BOOTS: 5
    - DIAMOND_HELMET: 10
    - DIAMOND_CHESTPLATE: 15
    - DIAMOND_LEGGINGS: 10
    - DIAMOND_BOOTS: 10
    - NETHERITE_HELMET: 10
    - NETHERITE_CHESTPLATE: 15
    - NETHERITE_LEGGINGS: 10
    - NETHERITE_BOOTS: 10
    - ELYTRA: 50
    - IRON_SWORD: 1
    - IRON_PICKAXE: 1
    - IRON_AXE: 1
    - DIAMOND_SWORD: 3
    - DIAMOND_PICKAXE: 3
    - DIAMOND_AXE: 3
    - NETHERITE_SWORD: 10
    - NETHERITE_PICKAXE: 10
    - NETHERITE_AXE: 10
    - GOLDEN_APPLE: 10
    - ENCHANTED_GOLDEN_APPLE: 20
  max-affinity-changes:
    affinity-limit: 700
    points-per-minute: -3
    block-mined: -2
    player-hit: 1
    pvp-kill: -5
    pve-kill: -1
    death: 100
    items-held-or-worn:
    - IRON_HELMET: -1
    - IRON_CHESTPLATE: -2
    - IRON_LEGGINGS: -1
    - IRON_BOOTS: -1
    - DIAMOND_HELMET: -3
    - DIAMOND_CHESTPLATE: -4
    - DIAMOND_LEGGINGS: -3
    - DIAMOND_BOOTS: -3
    - NETHERITE_HELMET: -5
    - NETHERITE_CHESTPLATE: -8
    - NETHERITE_LEGGINGS: -5
    - NETHERITE_BOOTS: -5
    - ELYTRA: -10
    - IRON_SWORD: -1
    - IRON_PICKAXE: -1
    - IRON_AXE: -1
    - DIAMOND_SWORD: -3
    - DIAMOND_PICKAXE: -3
    - DIAMOND_AXE: -3
    - NETHERITE_SWORD: -5
    - NETHERITE_PICKAXE: -5
    - NETHERITE_AXE: -5
    - GOLDEN_APPLE: -5
    - ENCHANTED_GOLDEN_APPLE: -20