main: me.skinnyjeans.gmd.Main
name: DynamicDifficulty
version: 1.0.04
author: SkinnyJeans
api-version: 1.13
softdepend: [PlaceholderAPI]

permissions:
  affinity.*:
    default: op
    children:
      affinity.get: true
      affinity.author: true
      affinity.add: true
      affinity.remove: true
      affinity.removemax: true
      affinity.set: true
      affinity.setmax: true

  affinity.get:
    default: false
    description: Allows a player to look up a someones affinity
  affinity.author:
    default: false
    description: Returns the authors name
  affinity.set:
    default: op
    description: Allows a player to set
  affinity.remove:
    default: op
    description: Allows a player to remove a certain amount of affinity to someone
  affinity.add:
    default: op
    description: Allows a player to add a certain amount of affinity to someone
  affinity.setmax:
    default: op
    description: Allows a player to set a max affinity for someone
  affinity.removemax:
    default: op
    description: Allows a player to remove a max affinity for someone

commands:
  affinity:
    description: Settings to change the Affinity of users